# vLLM 컨테이너 정의

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "${LLM_API_PORT:-8000}:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    # ← 윈도우에서 옵션 누락 방지용으로 '배열' 형식 사용
    command: [
      "--model", "${LLM_MODEL}",
      "--host", "0.0.0.0",
      "--max-model-len", "2048",
      "--gpu-memory-utilization", "0.70",
      "--dtype", "auto",
      "--tensor-parallel-size", "1"
    ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    pull_policy: always

# 실행
# docker compose up -d

# 로그 보기 (서버가 모델 다운로드/로드 중이면 시간이 조금 걸림)
# docker compose logs -f

# T_project 말고
# cd C:\Users\user\Documents\Github\T_project\ai\llama-runtime
# 위 경로에서 실행해야 함

